services:
  redis:
    image: redis:7-alpine
    container_name: my_redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn --bind 0.0.0.0:8000 netology_pd_diplom.wsgi:application"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build: .
    command: celery -A netology_pd_diplom worker --loglevel=info
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A netology_pd_diplom beat --loglevel=info
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  static_volume:
